from __future__ import annotations

import json
from pathlib import Path


def _load_json(path: str | Path) -> dict:
    with Path(path).open("r", encoding="utf-8") as fh:
        return json.load(fh)


def render_experiment_table(summary_path: str | Path, output_path: str | Path) -> str:
    summary = _load_json(summary_path)
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as fh:
        fh.write("% Auto-generated by SIREN\n")
        fh.write("\\begin{table}[t]\n\\centering\n")
        fh.write("\\caption{Synthetic experiment risk summary.}\n")
        fh.write("\\begin{tabular}{lccc}\n\\toprule\n")
        fh.write("Module & Mean Risk & Blocked Rate & 95\\% CI \\\\\n\\midrule\n")
        for name, row in summary.items():
            fh.write(
                f"{name.replace('_', ' ')} & {float(row.get('mean_risk', 0.0)):.3f} & "
                f"{float(row.get('blocked_rate', 0.0)):.3f} & "
                f"[{float(row.get('ci_low', 0.0)):.3f}, {float(row.get('ci_high', 0.0)):.3f}] \\\\\n"
            )
        fh.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    return str(out)


def render_ablation_table(summary_path: str | Path, output_path: str | Path) -> str:
    summary = _load_json(summary_path)
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as fh:
        fh.write("% Auto-generated by SIREN\n")
        fh.write("\\begin{table}[t]\n\\centering\n")
        fh.write("\\caption{SIREN-WAVE ablation summary.}\n")
        fh.write("\\begin{tabular}{lccc}\n\\toprule\n")
        fh.write("Variant & Mean Risk & Blocked Rate & p-value vs full \\\\\n\\midrule\n")
        for name, row in summary.items():
            fh.write(
                f"{name.replace('_', ' ')} & {float(row.get('mean_risk', 0.0)):.3f} & "
                f"{float(row.get('blocked_rate', 0.0)):.3f} & {float(row.get('pvalue_vs_full', 1.0)):.4f} \\\\\n"
            )
        fh.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")
    return str(out)
